Controllers/AttendancesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using PERM.Constants;
using PERM.Data;
using PERM.Models;

namespace PERM.Controllers
{
    [Authorize(Roles = "SuperAdmin,PowerUser,HrAdmin ,BasicUser, ProjectManager_TeamLead")]
    public class AttendancesController : Controller
    {
        private readonly ApplicationDbContext _context;

        public AttendancesController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Attendances
        public async Task<IActionResult> Index()
        {
              return _context.attendance != null ? 
                          View(await _context.attendance.ToListAsync()) :
                          Problem("Entity set 'ApplicationDbContext.attendance'  is null.");
        }

        // GET: Attendances/Details/5
        public async Task<IActionResult> Details(string id)
        {
            if (id == null || _context.attendance == null)
            {
                return NotFound();
            }

            var attendance = await _context.attendance
                .FirstOrDefaultAsync(m => m.AttendanceID == id);
            if (attendance == null)
            {
                return NotFound();
            }

            return View(attendance);
        }

        // GET: Attendances/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Attendances/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("AttendanceID,EmployeeID,Status,AttendanceDate,AttendanceInTime,AttendanceOutTime")] Attendance attendance)
        {
            if (ModelState.IsValid)
            {
                _context.Add(attendance);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(attendance);
        }

        // GET: Attendances/Edit/5
        public async Task<IActionResult> Edit(string id)
        {
            if (id == null || _context.attendance == null)
            {
                return NotFound();
            }

            var attendance = await _context.attendance.FindAsync(id);
            if (attendance == null)
            {
                return NotFound();
            }
            return View(attendance);
        }

        // POST: Attendances/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(string id, [Bind("AttendanceID,EmployeeID,Status,AttendanceDate,AttendanceInTime,AttendanceOutTime")] Attendance attendance)
        {
            if (id != attendance.AttendanceID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(attendance);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!AttendanceExists(attendance.AttendanceID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(attendance);
        }

        // GET: Attendances/Delete/5
        public async Task<IActionResult> Delete(string id)
        {
            if (id == null || _context.attendance == null)
            {
                return NotFound();
            }

            var attendance = await _context.attendance
                .FirstOrDefaultAsync(m => m.AttendanceID == id);
            if (attendance == null)
            {
                return NotFound();
            }

            return View(attendance);
        }

        // POST: Attendances/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(string id)
        {
            if (_context.attendance == null)
            {
                return Problem("Entity set 'ApplicationDbContext.attendance'  is null.");
            }
            var attendance = await _context.attendance.FindAsync(id);
            if (attendance != null)
            {
                _context.attendance.Remove(attendance);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool AttendanceExists(string id)
        {
          return (_context.attendance?.Any(e => e.AttendanceID == id)).GetValueOrDefault();
        }
    }
}

Controllers/DepartmentsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using PERM.Constants;
using PERM.Data;
using PERM.Models;

namespace PERM.Controllers
{
    [Authorize(Roles = "SuperAdmin,PowerUser,HrAdmin ,BasicUser, ProjectManager_TeamLead")]

    public class DepartmentsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public DepartmentsController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Departments
        public async Task<IActionResult> Index()
        {
              return _context.department != null ? 
                          View(await _context.department.ToListAsync()) :
                          Problem("Entity set 'ApplicationDbContext.department'  is null.");
        }

        // GET: Departments/Details/5
        public async Task<IActionResult> Details(string id)
        {
            if (id == null || _context.department == null)
            {
                return NotFound();
            }

            var department = await _context.department
                .FirstOrDefaultAsync(m => m.DeptID == id);
            if (department == null)
            {
                return NotFound();
            }

            return View(department);
        }

        // GET: Departments/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Departments/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("DeptID,DeptNo,DepartmentName")] Department department)
        {
            if (ModelState.IsValid)
            {
                _context.Add(department);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(department);
        }

        // GET: Departments/Edit/5
        public async Task<IActionResult> Edit(string id)
        {
            if (id == null || _context.department == null)
            {
                return NotFound();
            }

            var department = await _context.department.FindAsync(id);
            if (department == null)
            {
                return NotFound();
            }
            return View(department);
        }

        // POST: Departments/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(string id, [Bind("DeptID,DeptNo,DepartmentName")] Department department)
        {
            if (id != department.DeptID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(department);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!DepartmentExists(department.DeptID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(department);
        }

        // GET: Departments/Delete/5
        public async Task<IActionResult> Delete(string id)
        {
            if (id == null || _context.department == null)
            {
                return NotFound();
            }

            var department = await _context.department
                .FirstOrDefaultAsync(m => m.DeptID == id);
            if (department == null)
            {
                return NotFound();
            }

            return View(department);
        }

        // POST: Departments/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(string id)
        {
            if (_context.department == null)
            {
                return Problem("Entity set 'ApplicationDbContext.department'  is null.");
            }
            var department = await _context.department.FindAsync(id);
            if (department != null)
            {
                _context.department.Remove(department);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool DepartmentExists(string id)
        {
          return (_context.department?.Any(e => e.DeptID == id)).GetValueOrDefault();
        }
    }
}

Controllers/_TasksController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using PERM.Data;
using PERM.Models;

namespace PERM.Controllers
{
    
    public class _TasksController : Controller
    {
        private readonly ApplicationDbContext _context;

        public _TasksController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: _Tasks
        public async Task<IActionResult> Index()
        {
              return _context._tasks != null ? 
                          View(await _context._tasks.ToListAsync()) :
                          Problem("Entity set 'ApplicationDbContext._tasks'  is null.");
        }

        // GET: _Tasks/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context._tasks == null)
            {
                return NotFound();
            }

            var _Tasks = await _context._tasks
                .FirstOrDefaultAsync(m => m.TaskID == id);
            if (_Tasks == null)
            {
                return NotFound();
            }

            return View(_Tasks);
        }

        // GET: _Tasks/Create
        [Authorize(Roles= "SuperAdmin, BasicUser")]
        public IActionResult Create()
        {
            return View();
        }

        [Authorize(Roles = "SuperAdmin")]

        // POST: _Tasks/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("TaskID,TaskName,TaskDescription,TaskStatus,TaskType,TaskCreatedDate,TaskUpdatedDate,TaskDeadline,TaskCompletionDate,TaskAssignedTo,TaskAssignedBy")] _Tasks _Tasks)
        {
            if (ModelState.IsValid)
            {
                _context.Add(_Tasks);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(_Tasks);
        }
        [Authorize(Roles = "SuperAdmin")]
        // GET: _Tasks/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context._tasks == null)
            {
                return NotFound();
            }

            var _Tasks = await _context._tasks.FindAsync(id);
            if (_Tasks == null)
            {
                return NotFound();
            }
            return View(_Tasks);
        }

        [Authorize(Roles = "SuperAdmin")]
        // POST: _Tasks/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("TaskID,TaskName,TaskDescription,TaskStatus,TaskType,TaskCreatedDate,TaskUpdatedDate,TaskDeadline,TaskCompletionDate,TaskAssignedTo,TaskAssignedBy")] _Tasks _Tasks)
        {
            if (id != _Tasks.TaskID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(_Tasks);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!_TasksExists(_Tasks.TaskID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(_Tasks);
        }

        [Authorize(Roles = "SuperAdmin")]

        // GET: _Tasks/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context._tasks == null)
            {
                return NotFound();
            }

            var _Tasks = await _context._tasks
                .FirstOrDefaultAsync(m => m.TaskID == id);
            if (_Tasks == null)
            {
                return NotFound();
            }

            return View(_Tasks);
        }

        [Authorize(Roles = "SuperAdmin")]

        // POST: _Tasks/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context._tasks == null)
            {
                return Problem("Entity set 'ApplicationDbContext._tasks'  is null.");
            }
            var _Tasks = await _context._tasks.FindAsync(id);
            if (_Tasks != null)
            {
                _context._tasks.Remove(_Tasks);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool _TasksExists(int id)
        {
          return (_context._tasks?.Any(e => e.TaskID == id)).GetValueOrDefault();
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - PERM</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/PERM.styles.css" asp-append-version="true" />
    <link href="~/css/permstylesheet.css" rel="stylesheet" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
           <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">PERM</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        @if(User.Identity.IsAuthenticated){
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="EmployeeMasterDatas" asp-action="Index">EmployeeMasterData</a>
                        </li>
                        
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Departments" asp-action="Index">Department</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Attendances" asp-action="Index">Attendance</a>
                        </li>
                       
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="_Tasks" asp-action="Index">Task</a>
                        </li>
                        
                        }
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
                
            </div>
           
        </nav>
            @*
                side bar UI
            ---------------------------------------------------  
            <html>
            <head>

            </head>
            <body>
                <div class="area"></div>
                <nav class="main-menu">
                    <ul>
                        <li>
                            <a href="#">
                                <i class="fa fa-home fa-2x"></i>
                                <span class="nav-text">
                                    Dashboard
                                </span>
                            </a>

                        </li>
                        <li class="has-subnav">
                            <a href="#">
                                <i class="fa fa-globe fa-2x"></i>
                                <span class="nav-text">
                                    Employee Master Data
                                </span>
                            </a>

                        </li>
                        <li class="has-subnav">
                            <a href="#">
                                <i class="fa fa-comments fa-2x"></i>
                                <span class="nav-text">
                                    Attendance
                                </span>
                            </a>

                        </li>
                        <li class="has-subnav">
                            <a href="#">
                                <i class="fa fa-camera-retro fa-2x"></i>
                                <span class="nav-text">
                                    Tasks
                                </span>
                            </a>

                        </li>
                        <li>
                            <a href="#">
                                <i class="fa fa-film fa-2x"></i>
                                <span class="nav-text">
                                    Department
                                </span>
                            </a>
                        </li>
                        <li>
                            <a href="#">
                                <i class="fa fa-book fa-2x"></i>
                                <span class="nav-text">
                                    Surveying Jobs
                                </span>
                            </a>
                        </li>
                        <li>
                            <a href="#">
                                <i class="fa fa-cogs fa-2x"></i>
                                <span class="nav-text">
                                    Tools & Resources
                                </span>
                            </a>
                        </li>
                        <li>
                            <a href="#">
                                <i class="fa fa-map-marker fa-2x"></i>
                                <span class="nav-text">
                                    Member Map
                                </span>
                            </a>
                        </li>
                        <li>
                            <a href="#">
                                <i class="fa fa-info fa-2x"></i>
                                <span class="nav-text">
                                    Documentation
                                </span>
                            </a>
                        </li>
                    </ul>

                    <ul class="logout">
                        <li>
                            <a href="#">
                                <i class="fa fa-power-off fa-2x"></i>

                            @if (SignInManager.IsSignedIn(User))
                            {
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="Identity" asp-page="/Account/Manage/Index" title="Manage">Hello @User.Identity?.Name!</a>
                        </li>
                        <li class="nav-item">
                            <form class="form-inline" asp-area="Identity" asp-page="/Account/Logout" asp-route-returnUrl="@Url.Action("Index", "Home", new { area = "" })">
                                <button type="submit" class="nav-link btn btn-link text-dark">Logout</button>
                            </form>
                        </li>
                            }
                            else
                            {
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="Identity" asp-page="/Account/Register">Register</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="Identity" asp-page="/Account/Login">Login</a>
                        </li>
                            }
                                </span>
                            </a>
                        </li>
                    </ul>
                </nav>
            </body>
        </html>

        --------------------------------------------------------------------------------------------*@
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - PERM - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>